// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcuwakrhtojxhmshaikw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjdXdha3JodG9qeGhtc2hhaWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjg2NzQsImV4cCI6MjA2NTg0NDY3NH0.L3OhIGnv62-p_WQH_wV40JhQmAmzjjW_aS2LFdkbWiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);